name: Kubescape
# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   nsa-security-check:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Install Kubescape
#         run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash

#       - name: Scan YAML files
#         run: kubescape scan framework nsa *.yaml
        

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nsa-security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash
          sudo mv kubescape /usr/local/bin/

      - name: Scan YAML files
        run: |
          export PATH= .github/home/runner/.kubescape/bin
          kubescape scan framework nsa *.yaml



