# name: Kubescape

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   nsa-security-check:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Checkout
#         uses: actions/checkout@v2

#       - name: Install Kubescape
#         run: curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash

#       - name: Scan YAML files
#         run: kubescape scan framework nsa *.yaml


name: Kubescape

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  nsa-security-check:
    runs-on: ubuntu-latest

    steps:
      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Kubescape
        run: |
          curl -s https://raw.githubusercontent.com/armosec/kubescape/master/install.sh | /bin/bash

      - name: Set up Kubescape
        run: echo "::add-path::/home/runner/.kubescape/bin"

      - name: Scan YAML files
        run: |
          kubescape scan framework nsa *.yaml



